print(False & False)
print(False & True)
print(True & False)
print(True & True)
print()

print(False | False)
print(False | True)
print(True | False)
print(True | True)
print()

print(False ^ False)
print(False ^ True)
print(True ^ False)
print(True ^ True)
print()

print(~False)
print(~True)