import tkinter as tk

ventana = tk.Tk()
ventana.geometry("780x520+50+50")

etiqueta_arriba_1 = tk.Label(ventana, text="Arriba 1")
etiqueta_arriba_2 = tk.Label(ventana, text="Arriba 2")
etiqueta_arriba_3 = tk.Label(ventana, text="Arriba 3")
etiqueta_arriba_4 = tk.Label(ventana, text="Arriba 4")
etiqueta_arriba_5 = tk.Label(ventana, text="Arriba 5")
etiqueta_arriba_6 = tk.Label(ventana, text="Arriba 6")
etiqueta_arriba_7 = tk.Label(ventana, text="Arriba 7")
etiqueta_derecha_1 = tk.Label(ventana, text="Derecha 1")
etiqueta_derecha_2 = tk.Label(ventana, text="Derecha 2")
etiqueta_derecha_3 = tk.Label(ventana, text="Derecha 3")
etiqueta_derecha_4 = tk.Label(ventana, text="Derecha 4")
etiqueta_derecha_5 = tk.Label(ventana, text="Derecha 5")
etiqueta_izquierda_1 = tk.Label(ventana, text="Izquierda 1")
etiqueta_izquierda_2 = tk.Label(ventana, text="Izquierda 2")
etiqueta_abajo_1 = tk.Label(ventana, text="Abajo 1")
etiqueta_abajo_2 = tk.Label(ventana, text="Abajo 2")
etiqueta_abajo_3 = tk.Label(ventana, text="Abajo 3")
etiqueta_abajo_4 = tk.Label(ventana, text="Abajo 4")
etiqueta_abajo_5 = tk.Label(ventana, text="Abajo 5")
etiqueta_abajo_6 = tk.Label(ventana, text="Abajo 6")


etiqueta_arriba_1.pack(side=tk.TOP)
etiqueta_arriba_2.pack(side=tk.TOP)
etiqueta_arriba_3.pack(side=tk.TOP)
etiqueta_arriba_4.pack(side=tk.TOP)
etiqueta_arriba_5.pack(side=tk.TOP)
etiqueta_arriba_6.pack(side=tk.TOP)
etiqueta_arriba_7.pack(side=tk.TOP)
etiqueta_derecha_1.pack(side=tk.RIGHT)
etiqueta_derecha_2.pack(side=tk.RIGHT)
etiqueta_derecha_3.pack(side=tk.RIGHT)
etiqueta_derecha_4.pack(side=tk.RIGHT)
etiqueta_derecha_5.pack(side=tk.RIGHT)
etiqueta_izquierda_1.pack(side=tk.LEFT)
etiqueta_izquierda_2.pack(side=tk.LEFT)
etiqueta_abajo_1.pack(side=tk.BOTTOM)
etiqueta_abajo_2.pack(side=tk.BOTTOM)
etiqueta_abajo_3.pack(side=tk.BOTTOM)
etiqueta_abajo_4.pack(side=tk.BOTTOM)
etiqueta_abajo_5.pack(side=tk.BOTTOM)
etiqueta_abajo_6.pack(side=tk.BOTTOM)


ventana.mainloop()
